name: example-environment
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - catboost
  - dask
  - dill
  - eli5
  - lxml
  - matplotlib
  - numpy
  - pandas
  - partd
  - psutil
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - toolz
