name: example-environment
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bokeh
  - catboost
  - dask
  - dill
  - elephas
  - eli5
  - gensim
  - matplotlib
  - numpy
  - pandas
  - partd
  - psutil
  - toolz

  
  
